CREATE TABLE TIME_ENTRIES (
  ID         BIGINT(20) NOT NULL AUTO_INCREMENT,
  PROJECT_ID BIGINT(20),
  USER_ID    BIGINT(20),
  DATE       DATE,
  HOURS      INT,

  PRIMARY KEY (id)
)
  ENGINE = innodb
  DEFAULT CHARSET = utf8;